CREATE OR REPLACE FUNCTION INSERT_OBJECT_SUGGESTION(NAME_SUGGESTION VARCHAR(32),
                                                    DESCRIPTION_SUGGESTION VARCHAR(256),
                                                    NAME_OBJECT VARCHAR(32),
                                                    DESCRIPTION_OBJECT VARCHAR(256),
                                                    AUTHOR INTEGER)
    RETURNS VOID AS
$$
DECLARE
    OBJECT_ID     INT;
    SUGGESTION_ID INT;
BEGIN
    INSERT INTO OBJECT (NAME, DESCRIPTION, USER_ID)
    VALUES (NAME_OBJECT, DESCRIPTION_OBJECT, AUTHOR)
    RETURNING id INTO OBJECT_ID;
    INSERT INTO SUGGESTION (NAME, DESCRIPTION, CREATION_DATE, AUTHOR)
    VALUES (NAME_SUGGESTION, DESCRIPTION_SUGGESTION, CURRENT_TIMESTAMP, AUTHOR)
    RETURNING id INTO SUGGESTION_ID;
    INSERT INTO OBJECT_SUGGESTION (SUGGESTION, OBJECT)
    VALUES (SUGGESTION_ID, OBJECT_ID);
END;
$$ LANGUAGE PLPGSQL;