-- <--- INDEXES --->

CREATE INDEX REVIEW_INDEX_TARGET ON REVIEW USING HASH(TARGET);
CREATE INDEX OBJECT_INDEX_USER_ID ON OBJECT USING HASH(USER_ID);
CREATE INDEX SERVICE_INDEX_USER_ID ON SERVICE USING HASH(USER_ID);
CREATE INDEX OFFER_INDEX_NAME ON OFFER USING BTREE(NAME);
CREATE INDEX SUGGESTION_INDEX_NAME ON SUGGESTION USING BTREE(NAME);
CREATE INDEX OFFER_INDEX_CREATION_DATE ON OFFER USING BTREE(CREATION_DATE);
CREATE INDEX SUGGESTION_INDEX_CREATION_DATE ON SUGGESTION USING BTREE(CREATION_DATE);
CREATE INDEX WHEN_CAN_DO_INDEX_SERVICE_SUGGESTION ON WHEN_CAN_DO USING BTREE(SUGGESTION,SERVICE);
CREATE INDEX OBJECT_OFFER_REQUEST_INDEX_OFFER ON OBJECT_OFFER_REQUEST USING HASH(OFFER);
CREATE INDEX SERVICE_OFFER_REQUEST_INDEX_OFFER ON SERVICE_OFFER_REQUEST USING HASH(OFFER);
CREATE INDEX SUGGESTION_REQUEST_INDEX_SUGGESTION ON SUGGESTION_REQUEST USING HASH(SUGGESTION);

-- <--- TRIGGERS --->

CREATE OR REPLACE FUNCTION AFTER_DROP_SPECIFIC_OFFER_REQUEST()
    RETURNS TRIGGER AS
$$
DECLARE
    REQUEST INTEGER := (SELECT REQUEST
                        FROM OFFER
                        WHERE ID = OLD.REQUEST);
BEGIN
    DELETE FROM OFFER WHERE ID = REQUEST;
    RETURN NULL;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER AFTER_DROP_OBJECT_OFFER_REQUEST
    BEFORE DELETE
    ON OBJECT_OFFER_REQUEST
    FOR EACH ROW
EXECUTE PROCEDURE AFTER_DROP_SPECIFIC_OFFER_REQUEST();

CREATE TRIGGER AFTER_DROP_SERVICE_OFFER_REQUEST
    BEFORE DELETE
    ON SERVICE_OFFER_REQUEST
    FOR EACH ROW
EXECUTE PROCEDURE AFTER_DROP_SPECIFIC_OFFER_REQUEST();



CREATE OR REPLACE FUNCTION AFTER_DROP_SPECIFIC_COMMENT()
    RETURNS TRIGGER AS
$$
DECLARE
    COMMENT INTEGER := (SELECT COMMENT
                        FROM COMMENT
                        WHERE ID = OLD.REQUEST);
BEGIN
    DELETE FROM COMMENT WHERE ID = COMMENT;
    RETURN NULL;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER AFTER_DROP_SUGGESTION_COMMENT
    BEFORE DELETE
    ON SUGGESTION_COMMENT
    FOR EACH ROW
EXECUTE PROCEDURE AFTER_DROP_SPECIFIC_COMMENT();

CREATE TRIGGER AFTER_DROP_OFFER_COMMENT
    BEFORE DELETE
    ON OFFER_COMMENT
    FOR EACH ROW
EXECUTE PROCEDURE AFTER_DROP_SPECIFIC_COMMENT();



CREATE OR REPLACE FUNCTION AFTER_DROP_SPECIFIC_SUGGESTION()
    RETURNS TRIGGER AS
$$
DECLARE
    SUGGESTION INTEGER := (SELECT SUGGESTION
                           FROM SUGGESTION
                           WHERE ID = OLD.REQUEST);
BEGIN
    DELETE FROM SUGGESTION WHERE ID = SUGGESTION;
    RETURN NULL;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER AFTER_DROP_OBJECT_SUGGESTION
    BEFORE DELETE
    ON OBJECT_SUGGESTION
    FOR EACH ROW
EXECUTE PROCEDURE AFTER_DROP_SPECIFIC_SUGGESTION();

CREATE TRIGGER AFTER_DROP_SERVICE_SUGGESTION
    BEFORE DELETE
    ON SERVICE_SUGGESTION
    FOR EACH ROW
EXECUTE PROCEDURE AFTER_DROP_SPECIFIC_SUGGESTION();



CREATE OR REPLACE FUNCTION AFTER_DROP_SUGGESTION_REQUEST()
    RETURNS TRIGGER AS
$$
DECLARE
    REQUEST INTEGER := (SELECT REQUEST
                        FROM REQUEST
                        WHERE ID = OLD.REQUEST);
BEGIN
    DELETE FROM REQUEST WHERE ID = REQUEST;
    RETURN NULL;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER AFTER_DROP_SUGGESTION_REQUEST
    BEFORE DELETE
    ON SUGGESTION_REQUEST
    FOR EACH ROW
EXECUTE PROCEDURE AFTER_DROP_SUGGESTION_REQUEST();