CREATE TABLE DORMITORY
(
    ID          SERIAL PRIMARY KEY,
    NAME        VARCHAR(32) NOT NULL,
    ADDRESS     VARCHAR(128),
    DESCRIPTION VARCHAR(256)
);

CREATE TABLE "USER"
(
    ID            SERIAL PRIMARY KEY,
    NAME          VARCHAR(32)                                     NOT NULL,
    SURNAME       VARCHAR(32)                                     NOT NULL,
    EMAIL         VARCHAR(32)                                     NOT NULL,
    TELEPHONE     VARCHAR(16) CHECK (char_length(TELEPHONE) = 12) NOT NULL,
    PASSWORD      VARCHAR(128)                                    NOT NULL,
    PASSWORD_SALT VARCHAR(8)                                      NOT NULL,
    DORMITORY     INTEGER REFERENCES DORMITORY,
    RATING        REAL CHECK (RATING >= 0 AND RATING <= 5),
    IMAGE         BYTEA
);

CREATE TABLE REVIEW
(
    ID            SERIAL PRIMARY KEY,
    CONTENT       VARCHAR(32),
    CREATION_DATE TIMESTAMP WITH TIME ZONE                 NOT NULL,
    AUTHOR        INTEGER REFERENCES "USER"                NOT NULL CHECK (TARGET != AUTHOR),
    TARGET        INTEGER REFERENCES "USER"                NOT NULL CHECK (TARGET != AUTHOR),
    RATING        REAL CHECK (RATING >= 0 AND RATING <= 5) NOT NULL
);

CREATE TYPE "OBJECT_STATE" AS ENUM ('IN_STOCK', 'SHARED');

CREATE TYPE "STATUS" AS ENUM ('OPEN', 'CANCELED', 'RESOLVED');

CREATE TABLE OBJECT
(
    ID          SERIAL PRIMARY KEY,
    NAME        VARCHAR(32)  NOT NULL,
    DESCRIPTION VARCHAR(256) NOT NULL,
    IMAGE       BYTEA,
    STATE       "OBJECT_STATE" DEFAULT 'IN_STOCK',
    USER_ID     INTEGER REFERENCES "USER"
);

CREATE TABLE CATEGORY
(
    ID          SERIAL PRIMARY KEY,
    NAME        VARCHAR(32) NOT NULL,
    DESCRIPTION VARCHAR(256)
);

CREATE TABLE CATEGORY_OF_OBJECT
(
    OBJECT_ID   INTEGER REFERENCES OBJECT,
    CATEGORY_ID INTEGER REFERENCES CATEGORY,
    PRIMARY KEY (OBJECT_ID, CATEGORY_ID)
);

CREATE TABLE OBJECT_SUGGESTION
(
    ID        SERIAL PRIMARY KEY,
    SUGGESTON INTEGER REFERENCES SUGGESTON NOT NULL, -- ILYA'S TABLE
    OBJECT    INTEGER REFERENCES OBJECT    NOT NULL
);

CREATE TABLE OFFER
(
    ID            SERIAL PRIMARY KEY,
    DESCRIPTION   VARCHAR(256),
    STATUS        "STATUS"                 NOT NULL,
    CREATION_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    AUTHOR        INTEGER REFERENCES "USER"
);

CREATE TABLE OBJECT_OFFER
(
    ID     SERIAL PRIMARY KEY,
    OFFER  INTEGER REFERENCES OFFER  NOT NULL, -- ILYA'S TABLE
    OBJECT INTEGER REFERENCES OBJECT NOT NULL
);

CREATE TABLE SERVICE_OFFER
(
    ID      SERIAL PRIMARY KEY,
    OFFER   INTEGER REFERENCES OFFER   NOT NULL,
    SERVICE INTEGER REFERENCES SERVICE NOT NULL --ILYA'S TABLE
)