CREATE TRIGGER CHECK_STATUS
    BEFORE INSERT
    ON OBJECT_OFFER_REQUEST
    FOR EACH ROW
EXECUTE PROCEDURE CHECK_STATUS();

CREATE OR REPLACE FUNCTION CHECK_STATUS()
    RETURNS TRIGGER AS
$$
DECLARE
    STATE  INTEGER := (SELECT OBJECT_STATE
                       FROM OBJECT
                       WHERE ID = NEW.OBJECT);
    STATUS INTEGER := (SELECT STATUS
                       FROM OFFER
                       WHERE ID = NEW.OFFER);
BEGIN
    IF STATE == 'SHARED' OR STATUS != 'OPEN' THEN
        RETURN NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;